### ISSUE TITLE
Rework domains

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro.github.io#2]
@anhiga already added a simple header to send the users to the documentation. I would like to improve it a little bit adding the big version of the logo, an introductory paragraph and some details.

**Comment by astrojuanlu** [comment]
And we will likely turn this repository into https://www.poliastro.space, so it will need a proper navigatin menu as well.

**Comment by astrojuanlu** [comment]
Addressed in gh-45!

**Comment by astrojuanlu** [comment]
@jorgepiloto We are not in a hurry, but I just realized something:

This index page is still under https://blog.poliastro.space/ . It would be nice to have it under https://www.poliastro.space/, but then I assume that lots of things would break. So we would want a redirection instead.

We need to figure out which one of these two options we want:

- Have one repository for the index page at https://www.poliastro.space and another one for the blog https://blog.poliastro.space , each one with its own CNAME 
- Have one single repository for the index page and the blog at https://www.poliastro.space and redirect https://blog.poliastro.space to https://www.poliastro.space

I tried to quickly look for "how to redirect one subdomain to another subdomain" but didn't find an answer to what I was looking for. Let's give this some thought.

**Comment by astrojuanlu** [comment]
Also, blog urls now look like this:

https://blog.poliastro.space/blog/index.html

So... perhaps we can use `https://www.poliastro.space/blog/index.html` instead?

Still, keeping a redirection, at least for some time, would be necessary.

**Comment by astrojuanlu** [comment]
More annoyances (I just remembered this one):

https://blog.poliastro.space/blog/2021/01/24/2021-01-24-January-updates/

Can't we just have `https://*.poliastro.space/blog/2021/01/24/January-updates/` ?? 😅

**Comment by DhruvSondhi** [comment]
@astrojuanlu check this [article](https://medium.com/@hossainkhan/using-custom-domain-for-github-pages-86b303d3918a) out ... I do think so the URL is a GitHub page hosted one so you will need to change it ... Pelican config would also be changed according to need but first we need to figure out that if it's a GitHub one or something else :)

**Comment by astrojuanlu** [comment]
That article doesn't explain how to redirect `https://blog.domain.com` to `https://www.domain.com`, does it? Those steps are already in place for the current domain.

**Comment by DhruvSondhi** [comment]
> That article doesn't explain how to redirect `https://blog.domain.com` to `https://www.domain.com`, does it? Those steps are already in place for the current domain.

Don't know how relevant it may be ... checkout this [article](https://www.twilio.com/blog/redirect-github-to-custom-domain), [this](https://stackoverflow.com/questions/30167113/redirect-github-pages-to-custom-domain) too

**Comment by astrojuanlu** [comment]
I gave up on redirections, now all links are just broken :) Closing!
