### ISSUE TITLE
Make logo have a white background

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro.github.io#64]
See how this message in our Matrix chat looks when using a dark theme:

![Screenshot_2021-02-14 Element  1  poliastro](https://user-images.githubusercontent.com/316517/107875847-77f22200-6ec2-11eb-8e9e-fe5dd52cc468.png)

I think it's great that we keep a transparent version of the logo (so we can have things like cool black t-shirts like the ones @jorgepiloto made!) but, when including the text, we should use one with a white background.

Similar to what we did in https://github.com/poliastro/poliastro/issues/1022.

**Comment by DhruvSondhi** [comment]
> I think it's great that we keep a transparent version of the logo (so we can have things like cool black t-shirts like the ones @jorgepiloto made!) but, when including the text, we should use one with a white background.

Hello, Can you please specify which text does this point to?

**Comment by astrojuanlu** [comment]
@DhruvSondhi What text do you mean? Have you seen the screenshot?

**Comment by DhruvSondhi** [comment]
I do understand that you may be pointing to the following text if I am not wrong? 🤔 
![image](https://user-images.githubusercontent.com/66117751/107877038-ea2d2b80-6eef-11eb-95ae-f689e6901dd2.png)
As from the screen shot, this seems to be invisible 😢

**Comment by astrojuanlu** [comment]
Oh sorry - I was referring to the whole textual part of the logo (the logotype). Therefore: poliastro | Astrodynamics in Python.

In any case, the whole logo (pictogram/isotype + logotype) should have a white background.

**Comment by DhruvSondhi** [comment]
> Oh sorry - I was referring to the whole textual part of the logo (the logotype). Therefore: poliastro | Astrodynamics in Python.
> 
> In any case, the whole logo (pictogram/isotype + logotype) should have a white background.

Sure, I do understand what you are trying to say ... Instead we can customise the logo with black on white, white on black & transparent one (as it is now) & use all these in the specific case scenario, we may be presented with? 🤔

**Comment by astrojuanlu** [comment]
...the scope of the issue is limited to one thing: putting a white background to the logo. Everything else can be discussed elsewhere.
