### ISSUE TITLE
Create CNAME file in sources

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro.github.io#7]
Adding a domain through the settings just creates a CNAME in the master branch, see https://github.com/poliastro/poliastro.github.io/commit/9e0ef96fb3da67852296db6ae9e3073b8f02c725 (note: this commit might have disappeared when you read this)

We should create it in the sources branch instead, so it stays when deploying the site. @anhiga this is yours!

**Comment by anhiga** [comment]
Fixed, see 564100376f05de80edfcc6ad0c7ee1991f2a5cf3. There is also another solution: using `ghp-import -c CNAME` which would be even easier, but I prefer this one.

**Comment by astrojuanlu** [comment]
Awesome! Just checked that the URL works:

http://blog.poliastro.space/

Closing!
