### ISSUE TITLE
Auto-deployment with Travis

### ISSUE THREAD

**Issue by anhiga** [poliastro/poliastro.github.io#8]
Travis CI is able to deploy to GitHub Pages after a successful build, using minimal configuration as shown [here](https://docs.travis-ci.com/user/deployment/pages/).
It works by doing `git push --force`, but that's what's currently  being done anyway.

It isn't a big change, since `.travis.yml` now is only doing
```bash
script:
- make publish-to-github-force
```
so I'm not sure if it is worth it.

**Comment by astrojuanlu** [comment]
oh, how I miss this right now :joy:

**Comment by anhiga** [comment]
It would be a really easy change (probably), but I don't see if it is worth it. Travis made the deployment in 1 min 30 sec. I don't know if, with this change, that time would improve.

**Comment by astrojuanlu** [comment]
You're right, it's probably not worth it. Let's leave this open in case we do it some day but it's working fine right now.

**Comment by astrojuanlu** [comment]
Closing this, the current solution is working well enough.
